server:
  port: 8082

# gRPC-?????? (?????? ????????? Netty ????)
grpc:
  server:
    port: 9092

spring:
  application:
    name: ORDER-SERVICE
  security:
    user:
      name: user
      password: pass
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice_order
    username: postgres
    password: erke
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
    metadata-map:
      gRPC_port: ${grpc.server.port}
